name: fintech_app
description: Application Fintech pour entrepreneurs et PME en Afrique de l'Ouest.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design & UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.0
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.0

  # Networking & API
  http: ^1.2.0
  dio: ^5.4.0

  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.3.3
  image_picker: ^1.0.7
  velocity_x: ^4.3.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
